### ISSUE TITLE
it only support jdk1.8 ?

### ISSUE THREAD

**Issue by wklong** [chenjianjx/sep4j#3]
java.lang.UnsupportedClassVersionError: org/sep4j/Ssio : Unsupported major.minor version 52.0 (unable to load class org.sep4j.Ssio)

**Comment by chenjianjx** [comment]
Yes.  Version 2.0 requires jdk 8.   Early versions only needs jdk 1.5.  You can use the old version:

https://github.com/chenjianjx/sep4j/tree/e2785befb39d66e6910f48f68a6f27196ee11311  

Note that jitpack has to be introduced as a remote maven repository.  Check the  readme: 

https://github.com/chenjianjx/sep4j/blob/e2785befb39d66e6910f48f68a6f27196ee11311/README.md

**Comment by wklong** [comment]
Thanks ,but the maven repository only have 2.0+,

**Comment by chenjianjx** [comment]
The early versions are not in the central maven repo, but in  jitpack.io 's maven repo

**Comment by wklong** [comment]
ok,thanks,solved
